name: ci-example-az-app
run-name: CI example az app
on:
  pull_request:
    branches: [master]
    paths:
      - '!iac/**'
env: 
  CUSTOMER: awesome
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      imagename: ${{ steps.publish-image-name.outputs.image }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '11'
          cache: 'maven'
      - name: Build Unit Testing
        run: mvn test
      - name: Build with Maven
        run: mvn clean package --file pom.xml
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - id: build-image
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/example-az-app:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/example-az-app:${{ github.sha }}
      - id: publish-image-name
        run: |
              echo "image=example-az-app:${{ github.sha }}" >> $GITHUB_OUTPUT
  dev:
    runs-on: ubuntu-latest
    environment: dev-env
    needs: build
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
              az extension add --name containerapp
      - id: publish-image-name
        run: |
              echo  "-------IMAGE---------"
              echo  ${{ needs.build.outputs.imagename }}
              echo  "-----------------"
              az containerapp update -n ${{ env.CUSTOMER }}-dev-demo-app   \
              -g ${{ env.CUSTOMER }}-dev-rg\
              --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{needs.build.outputs.imagename}}