name: ci-infra-example-az
run-name: CI Infra example az
on:
  push:
    branches:
      - "feature/**"
env:
  CUSTOMER: awesome
  REGION: eastus2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az group create -l ${{ env.REGION }} -n ${{ env.CUSTOMER }}-dev-rg

      - name: "Preview Infra"
        run: |
          az deployment group validate \
          --name ${{ env.CUSTOMER }}-dev-rg \
          --resource-group ${{ env.CUSTOMER }}-dev-rg\
          --template-file ${{ env.GITHUB_WORKSPACE }}/iac/infra.json \
          --parameters customer=${{ env.CUSTOMER }} \
          --parameters environment=dev
  dev:
    needs: build
    runs-on: ubuntu-latest
    environment: infra-prd-env
    steps:
      - name: "Deploy Infra"
        run: |
          az deployment group create \
          --name ${{ env.CUSTOMER }}-dev-rg-deploy \
          --resource-group ${{ env.CUSTOMER }}-dev-rg\
          --template-file ${{ env.GITHUB_WORKSPACE }}/iac/infra.json \
          --parameters customer=${{ env.CUSTOMER }} \
          --parameters environment=dev
